# Build stage
FROM golang:1.21 AS Builder
WORKDIR /app 
COPY main.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -o server main.go

# Runtime stage
FROM alpine:latest
WORKDIR /app
COPY --from=Builder /app/server .
CMD [ "./server" ]